env:
  DISPLAY: :99
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout GitHub repo
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v4.2.1
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: matrix.os == 'ubuntu-latest'
      name: Start Xvfb
      run: Xvfb $DISPLAY &
    - continue-on-error: true
      if: matrix.os == 'ubuntu-latest'
      name: Run tests on Linux
      uses: nick-fields/retry@v3.0.0
      with:
        command: mvn -B test -Dtest=!Record*
        max_attempts: 3
        timeout_minutes: 30
    - continue-on-error: true
      if: matrix.os == 'macos-latest'
      name: Run tests on Mac
      uses: nick-fields/retry@v3.0.0
      with:
        command: mvn -B test -Dtest=!Docker*,!Record*
        max_attempts: 3
        timeout_minutes: 30
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Run tests on Windows
      uses: nick-fields/retry@v3.0.0
      with:
        command: mvn -B test -Dtest=!Docker*
        max_attempts: 3
        timeout_minutes: 30
    - continue-on-error: true
      if: success() && matrix.os == 'ubuntu-latest' && matrix.java == '17' && !contains(github.ref,
        'pull')
      name: Upload analysis to SonarCloud
      run: 'mvn -B sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=bonigarcia-github
        -Dsonar.projectKey=io.github.bonigarcia:webdrivermanager

        '
    - continue-on-error: true
      if: success() && matrix.os == 'ubuntu-latest' && matrix.java == '17' && !contains(github.ref,
        'pull')
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.3.1
    - continue-on-error: true
      if: always() && matrix.os == 'windows-latest'
      name: Store recordings (only available in Windows)
      uses: actions/upload-artifact@v4.3.3
      with:
        name: webm-files
        path: 'C:\Users\runneradmin\Downloads\*.webm

          '
    strategy:
      matrix:
        java:
        - 17
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
